edition = "2021"
fn_args_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
max_width = 120
merge_derives = true
newline_style = "Native"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
